### ISSUE TITLE
Template editor in GLPI

### ISSUE THREAD

**Issue by Speirs47** [mateusznitka/protocolsmanager#15]
It would be nice if there would be an editor for template.php in GLPI, not necessary WYSIWYG, simple html editor would be enough. 
It could also include an option to show preview. I'm not really fluent with HTML so it took me 2 hours to modify template.php to my needs including generating new PDF with each change.

**Comment by mateusznitka** [comment]
I have some plans with user-frienldy editor but not for now, because there is a lot of other things to do with plugin. 

But can you describe me what exactly you edited in template and what you expect from future editor? Did you completely rebuilded template or just changed sizes, marigins etc? Can you send me some example pdf with your modifications?

Regards

**Comment by Speirs47** [comment]
![Bez nazwy](https://user-images.githubusercontent.com/40421338/85846304-e5bbd300-b7a5-11ea-89ea-19cf725434e5.png)

Here's one of my reports. I changed locations of content text, image, document number and that's it.

**Comment by mateusznitka** [comment]
Hi, I added in new release textarea above the table. Ofc it's not exactly what you have there but a little step forward. Moreover, you can now use fields: {owner}, {admin} and {cur_date} in your template to show user name, admin name and current date.

Regards
