### ISSUE TITLE
GLPI  9.2.2 Compatibility

### ISSUE THREAD

**Issue by AptoSx4** [mateusznitka/protocolsmanager#4]
Hello,

I installed the plugin in our GLPI 9.2.2, but in the plugins section it doesnt appear.
Is it only compatible with version 9.2 or I did something wrong?

Cheers!

**Comment by mateusznitka** [comment]
Hi,
Plugin should work fine with all GLPI versions higher than 9.1.

Please explain what do you mean by "installed" - did you install plugin from GLPI and then it disappeared or did you unzip plugin to GLPI plugins directory and it is not visible from GLPI?
Did you download plugin from **releases** tab or by clicking **clone or download** on main github page?
Plugin folder name must be "protocolsmanager" to be visible from GLPI, so if you downloaded it by "clone or download" button, you should change folder name from "protocolsmanager-master" to "protocolsmanager". 

Regards,
Mat

**Comment by AptoSx4** [comment]
Hey! Thanks for you fast reply, you are right i unzip the plugin and it didn't appear, but i fixed it changing folder name to protocolsmanager as you said.

I installed it and activate but when i try to generate a report it doesn't display or generate  anything. I reviewed permissions of the plugin with my superadmin profile and both box are checked.

![imagen](https://user-images.githubusercontent.com/60621992/73775415-962c2a80-4764-11ea-8227-274c792a9f5e.png)

If i try to come back a error box say:

"File /glpi/files/.../t_tmp/1-02042020.pdf." not found

![imagen](https://user-images.githubusercontent.com/60621992/73775570-edca9600-4764-11ea-90e3-fe4db120d035.png)

Also protocols manager not appear in Plugins Menu
![imagen](https://user-images.githubusercontent.com/60621992/73775486-b9ef7080-4764-11ea-8c9c-8b25a53aa1e3.png)

Can you help me?

Cheers!

**Comment by mateusznitka** [comment]
Hi,
I checked plugin in GLPI 9.2.2 and unfortunately it is not compatible. 
Since 9.3 version, GLPI has new update query generator which is recommended by devs and used in my plugin, but it not exists in 9.2.x versions. I didn't notice it, so sorry for disinformation. I will set correct version compatibility info in next release.

I will consider creating a new branch and release for older versions of GLPI like yours, but it's difficult to say when.

Regards, 
Mat
